### ISSUE TITLE
Move away from table based traces

### ISSUE THREAD

**Issue by danielcompton** [day8/re-frame-10x#108]
As part of this the "269 traces (clear)" message/link should be moved up to the top, out of the table headings, and into its own button.

**Comment by daiyi** [comment]
Were you thinking about moving more towards dashboard-based traces? What might it look like?

**Comment by danielcompton** [comment]
This was more about the literal `<table>` based implementation. The dashboard stuff is still on the cards, but I don't have a clear idea of what that would be yet.

**Comment by daiyi** [comment]
Ah! I have abstracted too much.

I have my eyes set on a flexbox rewrite of that table!

**Comment by superstructor** [comment]
Traces panel has been rewritten to use flexbox instead of table.
