### ISSUE TITLE
More control over trace filtering

### ISSUE THREAD

**Issue by danielcompton** [day8/re-frame-10x#120]
> " I want to maintain the entire history if possible. If for example, I'm currently only interested in an "events" trace, I have found it only maintains the most recent dozen or so events"

Possibly add a settings panel to control which events are captured (as opposed to filtered in the trace view)

> " Have checkboxes for each event type (events, subs, reagent, internals). Anything unchecked is NOT logged for this session, resulting in holding onto the events that matter for longer"
> "If there has to be a limit, then allow us to specify the max number of events to hold on to"

**Comment by kimo-k** [comment]
db14e69 seems satisfactory. 
- Checkboxes for types are available, but they only control the view, not what's logged.
- Use **Retain last * epochs** to record more traces at a time.
- Use **Ignore epochs for: :event_id** to avoid holding onto the events that _don't_ matter.
