### ISSUE TITLE
Add new "replay" button 

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-10x#155]
Add a new "replay" button which performs two steps:
1. resets `app-db` to the value it had prior to the current event, and then, once all consequent computation is complete (subscriptions have run and views have updated - dominoes 4,5,6), 
2. re-dispatches the current event.  

So it provides for an action replay of the "current event".  The one to which the user has navigated. 

Notes:
  - Any trace arising out of Step 1 is ignored (any change to `app-db` will trigger subscriptions and views)
  - All trace arising out of Step 2 forms a normal epoch which is appended to the end of the existing epoch list, AND the user is transported to view this new epoch. So they immediately see the results for this new epoch. 
  - Button should be visible/available in all tabs. 

Will be useful:
1. in the Timings tab to see if the numbers are stable across multiple runs. 
2. whenever we hotload (via figwheel) a fixed/altered event handler, subscription handler or view, and we want to test if our change works.  Figwheel+replayis lovely, simple debugging move. 

![image](https://user-images.githubusercontent.com/3033376/36339327-df22074c-1416-11e8-93ce-c6e346ca98e6.png)

**Open Questions:**  
1. should this button be visible if the user has "paused" collection of events?  Probably not. 
2. should it be muted as depicted?  Or strong blue?

**Comment by mike-thompson-day8** [comment]
I know I'm loading up this issue, but also ... while in the area ... get the spacing and wording right ... 

![image](https://user-images.githubusercontent.com/3033376/36336893-7ebaa9f8-13e0-11e8-9613-c7315d46af45.png)

**Comment by Gregg8** [comment]
Replay button UI added (and info button hooked up to Mike's document). Just needs connecting to the functionality.
