### ISSUE TITLE
Rename project to `re-frame-10x` 

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-10x#156]
Memorable.  More sizzle, less sausage. 

Maybe lead in with this "quote" at the top of an updated README

> You probably don't know this, I mean, how could you, but 10x programmers have a secret handshake. 
> There's also a clubhouse, Deca, where we hangout,  easily solving distributed state problems, and 
naming things perfectly.
> 
> But we do genuinely care about "regular" programmers, so it is my great pleasure to
> write this letter of recommendation for `re-frame-10x`.  It gives 
>  insight into the inner workings of your program which is a superpower
> for debugging and understanding.  Wear those X-ray glasses and be free of your false assumptions faster!!
> 
> Sincerely, 
> I-Type-100-Words-A-Minute-With-My-Toes 
> Deca Liaison Officer
> 

> **Update:**  so there's been some confusion. Obviously, when we use it, we're at 100x.  Please stop with all the new membership applications.

Did you smile?  Or, too crazy?

**Comment by mike-thompson-day8** [comment]
Preparatory work incoming:
https://github.com/Day8/re-frame-trace#of-sausage-and-sizzle

**Comment by mike-thompson-day8** [comment]
Okay, Daniel has now done the hard yards for the project renaming, which means we're almost ready for an announcement (of rename and latest features). 

I've now added that quote to the top of the new README.  I'm interested in opinions when you see it context.  I'm ready to rip it out if it doesn't work.  I'm a bit unsure.  Need feedback.

**Comment by danielcompton** [comment]
Announcement has been made in all of the usual places.
