### ISSUE TITLE
Is Pause Behaviour Correct?

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-10x#158]
![image](https://user-images.githubusercontent.com/3033376/36351094-63b1dc9e-14f8-11e8-84bf-c12a6a35edc5.png)

Currently, the moment I navigate backwards through Epochs, "pause mode" kicks in automatically and I have to manually un-pause.  I initially found this behaviors confusing, but even after I learned it, I found it didn't match the way I  wanted to work. 

As an alternative to current behavior, I propose that:
1.  pausing should not happen automatically. It should only happen when initiated by the user. Likewise un-pausing should always be explicit. 
2.  newly recorded Epochs are always added to the "end" of the Epoch list. 
3.  consequently, if the user navigates back through Epochs, and then interacts with the application so as to create a new Epoch (eg. they click a button), then the newly created Epoch is simply added to the end of Epochs, as any new Epoch would be.  Yes, the user has created something of a "fork" in history, but for each Epoch we know the prior state and the final state, so each it a bit standalone. There's just a list of them. Noone says they have to form a true history. 
4. Whenever a user creates a new Epoch, they are auto-navigated to this new Epoch (and they are always added to the end of the list). As a result, if I navigate "backwards", and then click a button (thus creating a new Epoch at a historical point, I will be auto-navigated to the new Epoch I have created which is at the end of the Epoch list. 
5. When in "paused" mode, no Epochs are recorded.

**Comment by danielcompton** [comment]
We've removed pause mode in 0.3.1, so we don't need to take this any further.
