### ISSUE TITLE
Event Tab:  unnecessary scrollbar thingos

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-10x#159]
![image](https://user-images.githubusercontent.com/3033376/36350903-99947a6e-14f4-11e8-9982-fe40866c6f6f.png)

----------

![image](https://user-images.githubusercontent.com/3033376/36350924-034208a0-14f5-11e8-85ce-1291aa988b7f.png)

**Comment by danielcompton** [comment]
Hmm, haven't seen this on macOS, although scrollbars are hidden by default there, will look into this.
