### ISSUE TITLE
Special treatment of :path interceptor in event tab?

### ISSUE THREAD

**Issue by Dexterminator** [day8/re-frame-10x#165]
When using the `:path` interceptor, the `:db` effect in the "Effects" panel of the "Events" tab is sometimes a bit hard to understand. It's possible to see that :path is in the list of interceptors, but not which path it actually is.

I have no idea of how difficult it would be, but a cool feature would be to indicate the `:path` next to the `:db` effect in the "Effects" panel in some way, as well as in the `:path` interceptor in the "Interceptors" panel.

**Comment by danielcompton** [comment]
This is a good idea, we've been considering adding a `:description` to interceptors which would let them provide a textual description of what they do for people to inspect.

**Comment by kimo-k** [comment]
I think https://github.com/day8/re-frame/pull/786 solves this. Implementation is pretty straightforward. 

I opt for a `:comment` key instead of a `:description`. Descriptions are re-frame's currency, so this key would be a description's description, which feels inarticulate.
