### ISSUE TITLE
Overlay shows wrong :closure-defines

### ISSUE THREAD

**Issue by heyarne** [Day8/re-frame-10x#170]
The overlay that is shown on `Ctrl + h` shows `:closure-defines {"re_frame_10x.trace.trace_enabled_QMARK_" true}`, should be `{"re_frame.trace.trace_enabled_QMARK_" true}` as per the README. I think the relevant place in the code is [here](https://github.com/Day8/re-frame-10x/blob/39259f6d034296e4fe2d3eb72dfa199ea7918903/src/day8/re_frame_10x/view/container.cljs#L158).

**Comment by danielcompton** [comment]
Thanks, good catch!
