### ISSUE TITLE
Subs panel - a way of easily seeing only subs that changed

### ISSUE THREAD

**Issue by Gregg8** [day8/re-frame-10x#174]
In a sea of subscriptions (sometimes several pages), it would be nice to easily see where the action actually took place (i.e. those subs where the value actually changed). This could be done in two ways:

1) Have another checkbox called say, "Only show changed subs" (words to be determined and in context with the checkbox already there)

2) Place an orange gleam icon at an appropriate place on the line (perhaps next to the sub name).

I prefer option 1 but even when this is off, the gleam could be shown as per option 2, so I really think both would be useful.

**Comment by MawiraIke** [comment]
Is this concept already implemented @Gregg8 or still up for enhancement?
Option 1 might be already implemented in the current `10x` version.

![ignored_subs](https://user-images.githubusercontent.com/38689046/155936406-53731d26-991c-4c8b-a4a9-ba687c63fe2a.jpg)

**Comment by Gregg8** [comment]
I wrote this nearly 4 years ago, and I suspect the checkbox wasn't there at the time. 

In any case, that doesn't answer by request as it only applies to layer 2 subs. And most subs are layer 3.

However, I suspect that the nice colour-coding of subs that have been `Created`, `Run`, `Discarded` and `Not-run` was either non-existent or did not stand out as well, and I have not perceived the issue in my recent uses. 

There's also a very nice filter to help us focus on what's interesting to us, so I think with all these, I'll just close the issue now.
