### ISSUE TITLE
Events filters in settings don't filter out events from the trace tab

### ISSUE THREAD

**Issue by talgiat** [day8/re-frame-10x#175]
They only filter events out of the events tab

**Comment by mudgen** [comment]
Plans to get this fixed soon?  It is tripping me up.

**Comment by danielcompton** [comment]
I don't have any more time left to work on this project at the moment, but would be happy to take a PR for it. The relevant code is in `day8.re-frame-10x.view.traces` in the `visible-traces` binding. 

You would need to 

* subscribe to ignored events
* iterate over the epochs to find any epochs that are for the ignored event then find the bounds of those epochs (maybe create a subscription to do this?)
* Then remove any traces that have a trace-id within the bounds of the epoch.

**Comment by Luke1298** [comment]
We have an event to track user interaction for auto logout purposes; which means interacting with the reframe console itself will trigger new events -- I've noticed that this setting also does not filter events from the "event history" section. I think it would be helpful if it did.

**Comment by Luke1298** [comment]
> We have an event to track user interaction for auto logout purposes; which means interacting with the reframe console itself will trigger new events -- I've noticed that this setting also does not filter events from the "event history" section. I think it would be helpful if it did. Thoughts? -- perhaps I misunderstand and that `history` section is specifically not supposed to filter out events.

Nevermind. I realized that this is what the `Ignore epochs` setting is. Sorry for the noise!
