### ISSUE TITLE
A hook to should exist to allow application-level opening (vis ^h)

### ISSUE THREAD

**Issue by Gnurdle** [day8/re-frame-10x#181]
It would be useful if there was a published hook that could be called from inside cljs code to cause the same effect intended by ^H (which is known to be "fiddly")

We have been having trouble getting 10x to launch, and we suspect it is because we are
using mousetrap to grab keys, and somehow ^H is getting eaten.

If we had this hook, we could launch it ourselves....

**Comment by danielcompton** [comment]
If you clear all of your settings (`day8.re_frame_10x.trace.factory_reset_BANG_()`), on the next load it should show the window by default. Until we add a public API for toggling, you can call 

```cljs
(mranderson047.re-frame.v0v10v2.re-frame.core/dispatch [:settings/user-toggle-panel])
```
