### ISSUE TITLE
Undeclared vars in cljs.tools.reader

### ISSUE THREAD

**Issue by hoopes** [Day8/re-frame-10x#184]
I start a brand-new reframe app with the command:

`lein new re-frame issue-demo +10x +aliases`

Edit the project.clj and upgrade the version of `re-frame-10x`:

    :profiles
    {:dev
        {:dependencies [[binaryage/devtools "0.9.4"]
                        [day8.re-frame/re-frame-10x "0.3.0"]]

Finally, `lein clean && lein dev` (The clean might be superstitious...)

    Compiling "resources/public/js/compiled/app.js" from ["src/cljs"]...
    WARNING: Use of undeclared Var cljs.tools.reader.reader-types/reader-error at line 9 resources/public/js/compiled/out/rewrite_clj/reader.cljs
    WARNING: Wrong number of args (2) passed to cljs.tools.reader/read-token at line 182 resources/public/js/compiled/out/rewrite_clj/reader.cljs
    Successfully compiled "resources/public/js/compiled/app.js" in 29.071 seconds.

Please let me know if there's any other info that I can provide. Thanks!

**Comment by danielcompton** [comment]
`rewrite-clj` looks suspicious, it's not something we use in 10x. Can you try again after moving your `~/.lein/profiles.clj` file out of the way? Following your reproduction steps on my computer, it all compiles fine without any warnings.

**Comment by danielcompton** [comment]
Will close this now, but please reopen if you have more info and can reproduce it without your `~/.lein/profiles.clj`.

**Comment by hoopes** [comment]
Sorry - I kept meaning to repro, but haven't had the time. Thanks for checking. Apologies.

**Comment by hoopes** [comment]
FWIW, it was `cljfmt` in the `profiles.clj`. I didn't investigate any further than that. Thanks again.
