### ISSUE TITLE
Option to not automatically switch to the latest epoch

### ISSUE THREAD

**Issue by prbroadfoot** [day8/re-frame-10x#190]
I'm using re-frame-10x in an app with a timeout that fires an event every 20 seconds. When that happens, the dashboard automatically updates to the latest epoch. This is often inconvenient because it disrupts me while I'm inspecting a previous epoch. I don't want to ignore the event because I may be interested in inspecting information about it, but I don't want to automatically switch to its epoch when it happens. Is there a way around this problem?

**Comment by danielcompton** [comment]
Probably the best workaround at the moment would be to ignore that event, and then unignore it when you do want to inspect it.

**Comment by mike-thompson-day8** [comment]
See settings option to ignore events

**Comment by kimo-k** [comment]
This always bugged me, too. Now in #389, the view will stick when you select any epoch but the latest.
