### ISSUE TITLE
Instructions / Tutorial for setting up for boot project

### ISSUE THREAD

**Issue by wontheone1** [day8/re-frame-10x#196]
Hello ! I have a boot project that I want to use 'reframe' and 're-frame-10x' for it.
I mostly use leiningen previously so not so good with boot tasks.

I guess boot should be able to use this with some tasks but it would be great to see some instructions / tutorials on how to use re-frame-10x in boot project.
Or just example boot task definition.

**Comment by netpyoung** [comment]
I found template for boot https://github.com/robjens/boot-reframe-10x
