### ISSUE TITLE
Ability to configure re-frame-10x through project.clj

### ISSUE THREAD

**Issue by Dexterminator** [day8/re-frame-10x#202]
We have a bunch of events (periodically polling ones) that we always want to ignore. Right now every developer has to manually enter these into the re-frame-10x settings panel. It would be very nice to be able to keep this config in version control, perhaps by allowing configuration in `project.clj` (that is then overridable in the re-frame-10x panel?).

I think something similar to how cljs-devtools solves this would be nice: https://github.com/binaryage/cljs-devtools/blob/master/docs/configuration.md

Example config:
```clojure
...
:compiler
 {:output-to       "..."
  :output-dir      "..."
  :main            "..."
  :external-config
    {:re-frame-10x/config
     {:epochs-to-retain            10
      :ignore-epochs-for           [:my-recurring-event :my-other-recurring-event]
      :sync-app-db-with-navigation true
      :filter-out-traces-for-ns    [:re-com.box :some-other-lib.core]
      :remove-low-level-trace-for  [:reagent :re-frame]}}}
```

**Comment by danielcompton** [comment]
I've thought about this a little bit, and until recently I would have been 100% for this, but now with the new [AOT cache](https://clojurescript.org/news/2018-03-28-shared-aot-cache), this kind of approach is going to be unsafe (I think?). I would really like to be able to do this kind of thing, but am not sure how best to do it. Closure Defines could also work, but might be a little bit ugly.

**Comment by Dexterminator** [comment]
I see! In that article, it looks like `:closure-defines` is the recommended approach. While indeed a bit ugly, I think this functionality is worth it.

**Comment by carylee** [comment]
@Dexterminator were you able to get the `:closure-defines` working? I want to get a list of ignored epochs configured for my team, but your example didn't work for me.

**Comment by danielcompton** [comment]
@carylee that was just a proposal, it hasn't been implemented yet. In the meantime, you could do something in JavaScript which wrote to local storage the default values you'd like to have. I know it's not ideal, but could be a workaround for now.

**Comment by p-himik** [comment]
A quote from the linked article:
> The AOT cache logic cannot handle the case where **shipping JARs** employ macros that consult the ambient environment in order to affect the code generated for the source shipped in those JARs.

Seems like it's relevant if and only if someone decides to build a full JAR with re-frame-10x and then use re-frame-10x from that JAR. I'd think that such a scenario is so rare that anyone attempting it should simply be aware of the dragons ahead and not expect anything.
