### ISSUE TITLE
Show/hide hotkey in non-English layouts

### ISSUE THREAD

**Issue by achikin** [Day8/re-frame-10x#207]
`Ctrl-h` shortcut does not work if non-english layout is active.
### Steps to reproduce:
1. Navigate to the app with re-frame-10x enabled
2. Switch keyboard layout to a non-English one (in my case Russian)
3. Press `ctrl-h`
### Expected behavior:
`re-frame-10x` panel is shown/hidden
### Actual behavior:
Nothing happens.

**Comment by achikin** [comment]
This happens because a particular char is checked here, not a keycode https://github.com/Day8/re-frame-10x/blob/master/src/day8/re_frame_10x.cljs#L173

**Comment by danielcompton** [comment]
A PR would be welcome for this to switch to the keycode. We've had quite a few issues with this toggling hotkey, so we may need to take a different approach in the future, but for now, happy to fix this issue.

**Comment by achikin** [comment]
@danielcompton https://github.com/Day8/re-frame-10x/pull/208
