### ISSUE TITLE
How can I see the list of events?

### ISSUE THREAD

**Issue by achikin** [Day8/re-frame-10x#213]
How can I see the list of events as I did in re-frisk?

**Comment by danielcompton** [comment]
You can go to the Trace tab and select to show only events, and disable the "Only show traces for this epoch?" checkbox.

<img width="536" alt="screenshot of google chrome 4-02-19 11-11-45 am" src="https://user-images.githubusercontent.com/811954/52183551-bbded500-286d-11e9-8649-be7b85e08b97.png">

I think that's what you're looking for? Let me know if I've got it wrong and you're thinking of something else.
