### ISSUE TITLE
Switch to using %23 instead of # characters

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-10x#216]
From Chrome

> [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

I'm not sure where this is coming from, I thought we had addressed this with the `day8.re-frame-10x.utils.macros/slurp-macro` macro. If someone is able to track this down that would be very helpful, even if you don't provide a PR.

**Comment by shen-tian** [comment]
Where are you seeing this @danielcompton?

I can replicate when using 10x with todomvc, but it stems from the CSS file: 

https://github.com/Day8/re-frame/blob/a68e907cdba3c6504f8dfb9d6b259ae5578bad7d/examples/todomvc/resources/public/todos.css#L192
