### ISSUE TITLE
Missing dependency on cljsjs/create-react-class

### ISSUE THREAD

**Issue by Deraen** [Day8/re-frame-10x#224]
Currently the bundled Reagent 0.6.0 uses create-react-class. However, re-frame-10x doesn't have dependency on `cljsjs/create-react-class` or other cljsjs libs used by Reagent. This is fine with Reagent up to 0.8.0 because users get the cljsjs libs through Reagent dependencies.

But Reagent 0.9.0 will drop dependency on create-react-class, so re-frame-10x breaks as the bundled Reagent can't find the create-react-class library, unless user adds direct dependency on create-react-class.

This can be tested with a project using Reagent 0.9.0-SNAPSHOT.

**Comment by danielcompton** [comment]
Thanks for the heads up, I'll look at updating this.
