### ISSUE TITLE
required namespace not find

### ISSUE THREAD

**Issue by vehas** [Day8/re-frame-10x#225]
I found this error after add re-frame-10x  to shadow-cljs project

> The required namespace "mranderson048.re-frame.v0v10v2.re-frame.core" is not available, 
> it was required by "day8/re_frame_10x/view/components.cljs".
> 

and my relate shadow-cljs setting is 

```
:builds {:app {:compiler-options
                           {:source-map true
                            :optimizations :none
                            :closure-defines {re-frame.trace/trace-enabled? true
                                                       "re_frame.trace.trace_enabled_QMARK_" true
                                                       "day8.re_frame.tracing.trace_enabled_QMARK_"  true}
                     :target :browser
                     :devtools { :preloads [devtools.preload
                                                       day8.re-frame-10x.preload]}
```

**Comment by snorremd** [comment]
Which version of re-frame-10x are you using? I had the same problem with `0.3.4-react16` (using Figwheel Main to compile). This version references an older `mranderson048.re-frame.v0v10v2` version than what was provided in the jar: `mranderson048/re_frame/v0v10v6`.

Clojars contains a version `0.3.6` and `0.3.6-react16` of re-frame-10x that compiled without problems. The README.md references only version `0.3.4` which is unfortunate considering the issue with the mismatching requirements and vendored re-frame code.

**Comment by oconn** [comment]
I also use *figwheel-main* to compile. Switching to `0.3.6` as @snorremd suggested did fix the above error, but is now throwing the following cljs compiler warning.

```bash

  var: cljs.core/pr-writer-impl is not public

  197  ;; Copied from cljs.core and modified to take a LimitedStringBufferWriter
  198  
  199  (defn pr-writer-impl [obj writer opts]
  200    (if (-limited? writer)
  201      writer
  202      (cljs.core/pr-writer-impl obj writer opts)))
            ^---
  203  
  204  (defn- pr-writer
  205    "Prefer this to pr-seq, because it makes the printing function
  206     configurable, allowing efficient implementations such as appending
  207     to a StringBuffer."

```

**Comment by snorremd** [comment]
@oconn I'm not seeing that issue. My setup is detailed below.

My `deps.edn`:

```clojure
{:deps {org.roman01la/cljss        {:mvn/version "1.6.3"}
        org.clojure/clojure        {:mvn/version "1.10.0"}
        org.clojure/clojurescript  {:mvn/version "1.10.439"}
        reagent                    {:mvn/version "0.8.1"}
        re-frame                   {:mvn/version "0.10.6"}
        metosin/reitit             {:mvn/version "0.2.10"}
        metosin/reitit-frontend    {:mvn/version "0.2.10"}
        metosin/reitit-spec        {:mvn/version "0.2.10"}}

        
        
 :paths ["src" "resources"]
 :aliases {:fig   {:extra-deps {com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}
                                com.bhauman/figwheel-main       {:mvn/version "0.1.9"}
                                ;; Dev deps
                                day8.re-frame/re-frame-10x {:mvn/version "0.3.6-react16"}
                                org.clojure/test.check     {:mvn/version "0.9.0"}
                                binaryage/devtools         {:mvn/version "0.9.10"}}
               ;; Omitted aliases}
```

And my figwheel config:

```clojure
^{:watch-dirs   ["test" "src"]
  :css-dirs     ["resources/public/css"]
  :auto-testing true
  :open-url "http://[[server-hostname]]:[[server-port]]"}

{:main            curation-client.app
 :closure-defines {"re_frame.trace.trace_enabled_QMARK_" true}
 :preloads        [day8.re-frame-10x.preload]}
```

**Comment by oconn** [comment]
@snorremd Just started figwheel-main up again this morning and the warning is no longer thrown. I did confirm that [`cljs.core/pr-writer-impl`](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/core.cljs#L10086) is a private function and is accessed [here](https://github.com/Day8/re-frame-10x/blob/master/src/day8/re_frame_10x/utils/pretty_print_condensed.cljs#L202). I'm not familiar with the implementation of CLJS-1702 (Warning when using private vars), but I would expect figwheel-main to report this by default?

**Comment by snorremd** [comment]
@oconn This is of course happening because of the compilation cache. The relevant namespaces are already compiled to js, so no recompilation means no warnings. Removing the `target` and `.cpcache` folders and starting a fresh dev build reintroduced the warnings for me. Though I don't think warnings about dev tooling using private symbols from other namespaces is a very big issue.

@vehas Did any of this solve your issue?

**Comment by danielcompton** [comment]
The next release of 10x will access the private var via var-quote so you won't get these warnings anymore. I think the other issue about the wrong version being used has also been resolved?
