### ISSUE TITLE
Cannot expand any maps

### ISSUE THREAD

**Issue by rbrother** [Day8/re-frame-10x#230]
Clicking on collapsed map "triangles" does not work (no expansion happens) in Google Chrome browser:
![image](https://user-images.githubusercontent.com/39167/52971978-0e69d680-33c2-11e9-87df-f16835151ee2.png)

Same problem happens in Firefox.

With Microsoft Edge the expansion works but there are other visual problems:
![image](https://user-images.githubusercontent.com/39167/52972180-a8318380-33c2-11e9-8e7f-b79faf2dd36d.png)

I am using:
[org.clojure/clojurescript "1.10.238"]
[reagent "0.8.1"]
[re-frame "0.10.6"]
[day8.re-frame/re-frame-10x "0.3.6-react16"]
[day8.re-frame/tracing "0.5.1"]

**Comment by mike-thompson-day8** [comment]
Please see this troubleshooting item in the README:
https://github.com/Day8/re-frame-10x#the-expansion-triangles-in-the-data-browsers-dont-work-any-more-but-they-used-to
