### ISSUE TITLE
Not Public figwheel-main Warnings

### ISSUE THREAD

**Issue by pwhittin** [day8/re-frame-10x#233]
After I add the following deps:
day8.re-frame/re-frame-10x {:mvn/version "0.3.7-react16"}
day8.re-frame/tracing {:mvn/version "0.5.1"}

I get the following warnings during compile:

[Figwheel:WARNING] Compile Warning resources/public/cljs-out/dev/rewrite_clj/reader.cljs line:181 col
umn:14

var: cljs.tools.reader/read-token is not public

176 (aget matches 0)
177 matches))))
178
179 (defn read-keyword
180 [^not-native reader initch]
181 (let [tok (cljs.tools.reader/read-token reader :keyword (read-char reader))
^---

and

[Figwheel:WARNING] Compile Warning resources/public/cljs-out/dev/rewrite_clj/parser/core.cljs line:14$
column:10

var: rewrite-clj.reader/whitespace? is not public

144
145 (defn- dispatch
146 [c]
147 (cond (nil? c) parse-eof
148 (identical? c delimiter) reader/ignore
149 (reader/whitespace? c) parse-whitespace

**Comment by danielcompton** [comment]
Thanks, this is fixed in https://github.com/clj-commons/rewrite-cljs/pull/18 but is waiting (partially on me) for a new release of rewrite-cljs.

**Comment by palfrey** [comment]
[0.4.5 release](https://github.com/clj-commons/rewrite-cljs/commit/8e1937678816203c562825bda04bd110329c0da4) should fix this now, but seems to need zprint to also update?

**Comment by palfrey** [comment]
Ah https://github.com/kkinnear/zprint/pull/147 :)

**Comment by kkinnear** [comment]
Zprint was updated to use rewrite-cljs 0.4.5 in zprint 1.0.0 (which wasn’t a particularly major release for zprint, but bumped the version to 1.0.0 since that seemed to be the recommendation for reasonably mature Clojure libraries).
