### ISSUE TITLE
upgrade to mranderson 0.5.0

### ISSUE THREAD

**Issue by benedekfazekas** [Day8/re-frame-10x#235]
hi folks,

just released mranderson 0.5.0. quite a few exciting fixes and new features and a big, long overdue code clean up.

There is a breaking change: the leiningen task got renamed to `inline-deps`. That said I looked at `re-frame-10x` when I started working on the new branch but did not see an easy/quick way to test if my changes break anything on the project. So give it a spin sooner than later if possible (`refactor-nrepl` and `cider-nrepl` is just got migrated), also I am available for a few more weeks to quickly fix issues if any occurs.

**Comment by danielcompton** [comment]
Thanks for the heads up! I'll take a look now.

**Comment by benedekfazekas** [comment]
cheers. the issues you filed are not blocking or you just manually fixed them?

**Comment by danielcompton** [comment]
Just manually fixed them. Thanks!
