### ISSUE TITLE
Add UI button to hide trace panel

### ISSUE THREAD

**Issue by danielcompton** [day8/re-frame-10x#238]
> It would already be an improvement if there was a ui button on the left to close the pane. I don't mind it being shown, but i can't hide it on mobile :-(

_Originally posted by @Heliosmaster in https://github.com/Day8/re-frame-10x/issues/204#issuecomment-495871983_

This would be good at the very least as a stopgap for mobile users who can't hide 10x with keyboard shortcuts.

**Comment by paulbutcher** [comment]
I've just hit this issue. It's not insurmountable, but it is  nuisance.

Is there a reason why the pull request above wasn't applied? I see that it's somewhat out of date: if I was to spend some time getting it back up to date is it something  you might consider applying?
