### ISSUE TITLE
Need help using with Shadow-CLJS

### ISSUE THREAD

**Issue by davidsavoie1** [Day8/re-frame-10x#239]
I would need some help understanding how to get started using re-frame-10x with Shadow-CLJS build tool. I know there is [some documentation](https://github.com/Day8/re-frame-10x/blob/master/docs/Advanced-Setup.md) on the topic in the docs, but I don't understand it enough to make it work.

I'm pretty new to Clojurescript and I'd like to create and app with Re-Frame and inspecting the app db's content is critical for my understanding. Would someone be willing to provide me with some detailed explanation on how to set this up, please? Or are there simpler ways to see what's going on without a full-fleged inspection tool like 10x?

Also, is this the right place to ask this kind of question?

**Comment by mike-thompson-day8** [comment]
@davidsavoie1 
you are right, this not the right place to ask .  This place is for reporting issues and feature requests for re-frame-10x.  

It sounds like you want beginners help on re-frame?  In which case, the #re-frame channel in http://clojurians.net/ might be a god place to ask.  

And be sure to read the docs.  Something like https://github.com/Day8/re-frame/blob/master/docs/External-Resources.md  might be very helpful to you.  
or there's a bigger app here:
https://github.com/jacekschae/conduit
