### ISSUE TITLE
Consider using SVG for right-/down-arrows that expand/collapse sections

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame-10x#241]
E.g. in `view/app_db.cljs` there's this code: `[:span.arrow (if open? "▼" "▶")]`.
The issue is that the appearance now depends on the font configuration of the browser and OS.
Here's how it looks in Google Chrome on my system:
![image](https://user-images.githubusercontent.com/4410314/59549686-03871300-8f6a-11e9-8a02-0ddc24b14cca.png)
And in Firefox:
![image](https://user-images.githubusercontent.com/4410314/59549694-1a2d6a00-8f6a-11e9-8e0a-1af592e6e8f8.png)

The down arrow is the same black one.
I can't really check, but apparently it's also [an issue in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11635143/) due to default font changes in Windows 10.

Because of such changes, maybe it makes sense to use SVG icons in general, not just for the arrows.

**Comment by danielcompton** [comment]
Great idea! I don't have time for this right now, but would take a PR for it. Otherwise I'll get to it eventually.

**Comment by superstructor** [comment]
This is released in 0.4.6.
