### ISSUE TITLE
Trace window (and the Subs window) no longer scrolls content

### ISSUE THREAD

**Issue by Gregg8** [Day8/re-frame-10x#246]
No matter how many items are in the list, it does not scroll.

A scrollbar is shown but it continues beyond the bottom of the page.

Using the element inspector, I see that the height of the window is basically the height of content itself, probably minus enough pixels to force the scrollbar to be displayed (that spans from top to bottom).

Addition: Same for the Subs window

**Comment by superstructor** [comment]
Fixed thanks to @Gregg8 and merged into master. 

Morale of the storey - use flexbox all the way down and don't use strange scrollable-content custom components for things that should be simple...
