### ISSUE TITLE
Remove the dependency on `create-react-class`

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame-10x#247]
`create-react-class` is unmaintained and is not needed for React 16.
Relevant PR in Reagent: https://github.com/reagent-project/reagent/pull/416/files

Personal motivation - I filed the issue mainly because I spent a few hours trying to understand why a new NPM dependency suddenly broke my build. Turns out, `create-react-class` depends on outdated `core-js@1` and the new dependency brings in a transitive dependency on `core-js@2` (also outdated, but not as much so).

**Comment by superstructor** [comment]
Thanks for the report @p-himik 

My understanding is that the change in reagent is unreleased and part of the upcoming `0.9.0` release.

Once reagent `0.9.0` is released I'll release new versions of re-frame, re-frame-10x etc to use that version and no longer depend on `create-react-class`.

**Comment by kennyjwilli** [comment]
@superstructor 0.9.0 is out now. It'd be great to get a release without create-react-class :smiley:

**Comment by superstructor** [comment]
`0.5.1` has been released without create-react-class.
