### ISSUE TITLE
Using re-frame-10x with re-posh

### ISSUE THREAD

**Issue by filipesilva** [day8/re-frame-10x#255]
Heya,

https://github.com/denistakeda/re-posh adds datascript subscription support to re-frame. It uses a datascript database for these subscriptions instead of re-frame's `app-db`.

Is there a good way to see this database in re-frame-10x?

Thanks!

**Comment by mike-thompson-day8** [comment]
`app-db` is currently a map (inside a ratom).  Whereas a `datascript` database is an entirely different beast.  So it would be a substantial change (complete rewrite?) and one we're not likely to undertake within re-frame-10x.

**Comment by filipesilva** [comment]
Gotcha, thanks for the quick reply!
