### ISSUE TITLE
app-db path inspector expands/collapses all paths. Allow individual control

### ISSUE THREAD

**Issue by hipitihop** [day8/re-frame-10x#265]
When there are multiple path inspectors defined, when you click on the collection expand/collapse arrow to see the coll, e.g. a map, all other path inspectors  expand/collapse. 

It should be possible to individually control each inspector, so that you can keep some collapsed while inspecting others.

**Comment by superstructor** [comment]
Tested on latest `master` and can no longer reproduce the issue as described.
