### ISSUE TITLE
Make use of new Chrome performance measurement APIs?

### ISSUE THREAD

**Issue by danielcompton** [day8/re-frame-10x#28]
I'm not sure what/how we might use these, but they might be worth looking at a bit later in the summer. https://developers.google.com/web/updates/2017/06/user-centric-performance-metrics

**Comment by danielcompton** [comment]
https://calendar.perfplanet.com/2017/tracking-cpu-with-long-tasks-api/

**Comment by mike-thompson-day8** [comment]
Better interaction with the [chrome profile API](https://developers.google.com/web/tools/chrome-devtools/console/console-reference#profile).  
See also `console.timeStamp([label])`
