### ISSUE TITLE
Fixing the odd text formatting

### ISSUE THREAD

**Issue by eoyath** [day8/re-frame-10x#290]
The text formatting is screwed up for me on Firefox and Chrome, for the demo and local. The font sizes, the text overlaps, they are at different heights.

I would like to help, but considering how popular this library is, I assume someone else must have noticed this as well. How could I help to fix this?

![Screenshot_2021-02-24 Conduit](https://user-images.githubusercontent.com/74038200/109080326-5832d900-76ce-11eb-95ef-4c7465e12d61.png)

**Comment by superstructor** [comment]
I can't reproduce. What re-frame-10x version are you using ? Are you zooming the page ? It appears as follows for me:

![image](https://user-images.githubusercontent.com/350450/109237519-921eef00-7836-11eb-9eb8-c6f7b82933bc.png)

**Comment by celwell-reify** [comment]
I'm seeing the same issue; even in pop-out window mode (so it doesn't seem to be caused by my other CSS). Version: `[day8.re-frame/re-frame-10x "0.3.7"]`

**Comment by superstructor** [comment]
At this point the best information I have is that this only impacts old releases. We only maintain the latest version, i.e. `[day8.re-frame/re-frame-10x "1.0.1"]`.  To use that, you obviously also need to be using reagent 1.0.x, re-frame 1.2.x and React 17.0.x.

Please re-open the issue if you see it with the current release.
