### ISSUE TITLE
Trace Panel Issues

### ISSUE THREAD

**Issue by Gregg8** [day8/re-frame-10x#297]
![image](https://user-images.githubusercontent.com/3037372/112902182-807c8000-9131-11eb-98f8-5f081ea964ea.png)

Do feel free to add to this issue, but so far:

Annoying:
 - [x] The `XXX traces` column is very hard to read as it doesn't always show the full name of the event, even when there's plenty of space
 - [x] Clicking the open arrow on the left of the event to see the detail is slow, even when there is a small amount of data, and especially when you are showing more than a single event at a time. Sometimes it seems to freeze the UI completely
 - [x] When an event is open, you get the option to copy it to the console.  It would be best if this feature was available for all un-opened events
- [x] The "clear" also clears prior filterers like "events" "subscriptions" etc
Visual:
 - [x] This is the only panel that didn't receive any UI love. It needs to be styled in the image of the other tabs

**Comment by superstructor** [comment]
All issues should be resolved as of next release.
