### ISSUE TITLE
CSS issues in 1.1.0

### ISSUE THREAD

**Issue by eneroth** [day8/re-frame-10x#303]
See screenshot.

![Screenshot 2021-05-25 at 11 17 09](https://user-images.githubusercontent.com/333974/119473258-48697600-bd4b-11eb-8ef1-12aebb62c5d9.png)

Not exactly sure what's going on here, but the CSS seems broken. Happens regardless of browser used.

**Comment by superstructor** [comment]
@eneroth Can you please try version `1.1.1` for the event history (top) issue ?

**Comment by eneroth** [comment]
Sure! 

The event history is now a scrollable list:

https://user-images.githubusercontent.com/333974/119616213-a2784300-be00-11eb-8bb9-3ca6279134fb.mov

Subs are as before.

**Comment by MawiraIke** [comment]
This issue seems to be fixed in version `1.2.0`. The specific PR that fixed this is #325
@eneroth could you please try version `1.2.0`.

**Comment by MawiraIke** [comment]
I am closing this issue as it seems like a duplicate of #320 which is already fixed.
