### ISSUE TITLE
Relax hard requirement on LocalStorage

### ISSUE THREAD

**Issue by shepheb** [day8/re-frame-10x#308]
My (admittedly unusual) app architecture calls for running a re-frame app inside a sandboxed iframe. That works fine, but trying to add re-frame-10x during development causes errors.

re-frame-10x uses LocalStorage for saving various settings, and access to LocalStorage is blocked for sandboxed iframes.

It would be great if that code was tweaked to fail gracefully, rather than crash, if `window.localStorage` is unavailable. (One path might be to use the [`goog.testing.storage.FakeMechanism`](https://google.github.io/closure-library/api/goog.testing.storage.FakeMechanism.html) if a real one fails.)

**Comment by superstructor** [comment]
Would happily accept a pull request for `goog.testing.storage.FakeMechanism` if you are willing and able @shepheb 😉

**Comment by shepheb** [comment]
I'll take a look.
