### ISSUE TITLE
[Bug]: app-db is empty

### ISSUE THREAD

**Issue by awb99** [day8/re-frame-10x#313]
### What happened?

I upgraded from [day8.re-frame/re-frame-10x "1.0.2"] to "1.1.8". I did it in a batch with reagent 1.0.0 to reagent 1.1.0.
Now the 10x window looks much nicer, but appdb is always nil. My appdb is NOT nil.
Reagent now does no longer bring the react dependencies. Perhaps this is the problem?

### 10x Version

1.1.8

### Reagent Version

1.1.0

### React Version

17

### re-frame Version

1.2.0

### What browsers are you seeing the problem on?

Chrome

### Relevant console output

```shell
interestingly, there is no error nowhere.
I do one thing special, namely I hide 10x and I show it with my own keybinding.

BTW: I think the keybinding is really cool to have, but I would like to manage keybindings myself. So the fact that 10x adds its own keybindings is disturbing to me. It is alredy difficult enough to fin keybindings that work between multiple browsers. Having 10x block one keybinding is not what I want.
```

**Comment by awb99** [comment]
this error has disappeared after I removed all old shadow-cljs and node_modules artefacts. closing

**Comment by superstructor** [comment]
Thanks for following up @awb99 👍🏻 

I have raised #314 for user manageable keybindings.
