### ISSUE TITLE
[Enhancement]: User Manageable Keybindings

### ISSUE THREAD

**Issue by superstructor** [day8/re-frame-10x#314]
### What do you suggest?

re-frame currently hard-codes CTRL-H as a keybinding to show/hide the 10x panel.

This should be able to be turned off, and when turned on the specific keys used should be configurable. It should be able to be toggled programmatically.

It causes [users distress](https://github.com/day8/re-frame-10x/issues/313#issue-932177517) and [some projects have advanced dev tooling setups](https://github.com/athensresearch/athens/blob/37e0c88973a336036c9d5cba7cf9d586899d598b/src/cljs/athens/util.cljs#L313).

**Comment by sirmspencer** [comment]
Also, ctrl+h is pretty common as a hide button.  It can easily conflict with other tools.
