### ISSUE TITLE
[Bug]: Version 1.1.13 not compatible with highlight.js 11.1.0

### ISSUE THREAD

**Issue by P233** [day8/re-frame-10x#318]
### What happened?

After upgrading re-frame-10x to version `1.1.13` and highlight.js to `11.1.0`, when the mouse hovers over on a traced function, I got the following warning message in the console, and the function name is no longer highlighted in the code box.

<img width="935" alt="Screen Shot 2021-07-30 at 1 00 56 AM" src="https://user-images.githubusercontent.com/1818679/127534938-6a93ca4e-b22d-4367-919c-95e77567132b.png">

Downgrade highlight.js to `10.7.2`, works fine again.

### 10x Version

1.1.13

### Reagent Version

1.1.0

### React Version

17.0.2

### re-frame Version

1.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by kimo-k** [comment]
Highlight.js dependency is removed in 1.8
