### ISSUE TITLE
re-frame-10x uses cljs-devtools but completely overwrites its config

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame-10x#319]
### What do you suggest?

I have no idea why re-frame-10x does that, but if it needs some specific settings to be set to some specific values, two things are needed IMO:
- Document such a need, with all the keys and the values listed out, so that a user is not confused by something not working
- Overwrite only those values and don't touch the rest

Case in point - I need to set `:min-expandable-sequable-count-for-well-known-types` to 1. For some reason, re-frame-10x sets it to 3 making some values not expandable and incredibly long, going _way_ past the screen border.

**Comment by superstructor** [comment]
@MawiraIke Please change this so we only inject config that is required for 10x to work correctly, otherwise the behaviour should be to leave the devtools config as-is.

**Comment by MawiraIke** [comment]
Noted @superstructor 👍🏼

**Comment by MawiraIke** [comment]
Attached the PR above. I have tried to retain the look of the previous app-db as much possible. Open to making any changes to the configs.

**Comment by p-himik** [comment]
Just tried it - it doesn't solve the issue. re-frame-10x uses `devtools.prefs/default-config` but should be using `devtools.prefs/*current-config*` because otherwise any user changes are ignored.

The comment in the changed file says:
```
;; This used to be in the api-call fn below. However, recalculating this on *every* render is expensive so moved
;; here as static def.
```

But what about using `memoize` with a function accepting current `cljs-devtools` config as its argument? It would tick all the boxes.
