### ISSUE TITLE
[Bug]: app-db inspector incorrectly indents elements on "more" pagination

### ISSUE THREAD

**Issue by hipitihop** [day8/re-frame-10x#321]
### What happened?

When a list/vector is expanded, there is a limited number of elements shown followed but a button to show more elements. When pressed, more elements are shown, however they are rendered indented.

![image](https://user-images.githubusercontent.com/4626024/133164077-58e7157b-5fe1-4120-b028-8ed5c7ad5e2e.png)

### 10x Version

1.1.13

### Reagent Version

1.1.0

### React Version

17.0.2

### re-frame Version

1.2.0

### What browsers are you seeing the problem on?

Chrome

**Comment by superstructor** [comment]
@MawiraIke please have a look. at this.

**Comment by MawiraIke** [comment]
Okay @superstructor , I will post more information here after I reproduce the issue.
