### ISSUE TITLE
[Bug]: Clicking collapse / expand arrow icons always expands / collapses the whole app state

### ISSUE THREAD

**Issue by Jarzka** [day8/re-frame-10x#335]
### What happened?

When I click a little expand / collapse arrow icon to expand / collapse a part of the app state, it always expands / collapses the whole app state map, no matter what expand / collapse icon I click. It should expand / collapse only the clicked part of the app state, as it did previously.

### 10x Version

1.2.0

### Reagent Version

1.1.0

### React Version

17.0.2

### re-frame Version

1.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome

https://user-images.githubusercontent.com/5528061/144996735-00353d83-7156-4386-b02f-4c0328f6d9ee.mov

**Comment by MawiraIke** [comment]
@Jarzka could you please confirm if the path of items in the map are correct? In `10x` version `1.2.0` to keep state of opened maps and sequences, we use their path. If the object opens at every stage, I'm assuming that this would mean that the path of every object in the map is the same.
You can check the path by clicking on a keyword or number, where the path should be automatically filled in the input box.
You can also right click on a number or keyword and select copy path. 
Thank you.

**Comment by zalky** [comment]
Also seeing this on:

- re-frame-10x `1.2.0`
- reagent `1.0.0`
- react `17.0.1`

Additionally, either left or right clicking on a keyword or number does not automatically fill the input box (nothing happens).

**Comment by MawiraIke** [comment]
I am guessing that maybe the input box does not get updated because you have not updated the version of devtools manually yet. This has been mentioned in #332 .

**Comment by Jarzka** [comment]
I was able to fix this by manually adding the latest version of devtools as a dependency in my project.
