### ISSUE TITLE
[Bug]: UI doesn't update as you scroll through epochs in Event History panel

### ISSUE THREAD

**Issue by Gregg8** [day8/re-frame-10x#353]
When you press the back arrow any number of times (and forward arrow), or you click directly on an epoch, the UI remains unchanged.

I can confirm that `app-db` DOES correctly update, which makes it all the more confusing.

Is it updating a copy of `app-db`?

### 10x Version
1.2.3

### Reagent Version
1.1.0

### re-frame Version
1.2.0

### What browsers are you seeing the problem on?
Chrome

**Comment by Gregg8** [comment]
This should be added to: https://github.com/day8/re-frame-10x/issues/302

**Comment by superstructor** [comment]
@MawiraIke Please look at this only as bug fix on existing code. Don't attempt #302 yet. Thanks

**Comment by MawiraIke** [comment]
@superstructor looks like this functionality already exists in settings as `sync app-db with epoch navigation`. However, I find it to be a pain to have to switch it every time I need to "Time travel" and so I would suggest we also add it to `local-storage` for persistence during page reloads e.t.c.

**Comment by superstructor** [comment]
Thanks, agreed @MawiraIke
