### ISSUE TITLE
[Bug]: ReactJS 18 compatibility "ReactDOM.render is no longer supported in React 18"

### ISSUE THREAD

**Issue by n2o** [day8/re-frame-10x#367]
### What happened?

10x uses the old react API, which is not working in ReactJS 18. The following error message appears:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1507474/173436852-a832963f-189f-4dc5-a407-28f5a9bcea96.png">

To do this, we need to use the new functions for this. I built a project supporting the new react version and dropped 10x for this project: https://github.com/schnaq/cljs-re-frame-full-stack/blob/main/src/main/app/interface/core.cljs#L63-L67

### 10x Version

1.3.0

### Reagent Version

1.1.1

### React Version

18.1.0

### re-frame Version

1.2.0

### What browsers are you seeing the problem on?

Chrome

### Relevant console output

```shell
`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`.
```

**Comment by ceuk** [comment]
Should just be a case of updating [inject](https://github.com/day8/re-frame-10x/blob/master/src/day8/re_frame_10x.cljs#L124-L135) to use the new `create-root` and `render` functions from [reagent.dom.client](https://github.com/reagent-project/reagent/blob/master/src/reagent/dom/client.cljs) in Reagent 1.2.0 right?

**Comment by rpofuk** [comment]
I still get warning: 

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

Comming from day8.re-frame-10x.inlined-deps.reagent.v1v2v0.reagent.dom LN 17

![image](https://github.com/day8/re-frame-10x/assets/2906197/41f1b8fb-7201-44d6-bf75-915a0d308dd3)

I'm using {:mvn/version "1.9.3"}: 

> :preloads     [devtools.preload day8.re-frame-10x.preload.react-18]
