### ISSUE TITLE
[Bug]: react-highlight.js prevents me from updating to React 17

### ISSUE THREAD

**Issue by lilactown** [day8/re-frame-10x#381]
### What happened?

re-frame-10x requires us to install react-highlight.js in our project. This dependency hasn't been updated in years, and it declares a peer dependency of React 14/15/16. This makes it very awkward for us to update to React 17, since `npm` tries to keep peer dependencies honest, and I'm not sure if it has been tested at all.

[`react-highlight`](https://github.com/akiran/react-highlight) is an alternative that seems to be more up to date and from a cursory reading of the README, seems like it could be a drop in replacement.

### 10x Version

1.5.0

### Reagent Version

1.1.0

### React Version

17

### re-frame Version

1.2.0

**Comment by superstructor** [comment]
Correct. Was fixed in https://github.com/superstructor/re-highlight/pull/3

**Comment by kimo-k** [comment]
Fixed in b9edaa9
