### ISSUE TITLE
[Bug]: "Set literal contains duplicate key" when `*print-length*` is set

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame-10x#392]
### What happened?

Started in this Clojurians thread: [Set literal contains duplicate key](https://clojurians.slack.com/archives/C073DKH9P/p1688436193070349)

re-frame-10x uses `pr-str` in many places, this one being pertinent to the thread: https://github.com/day8/re-frame-10x/blob/e0b1bf4f95b2116f54c2d964f58c556cc7390593/src/day8/re_frame_10x/fx/local_storage.cljs#L56

The issue is that `pr-str` elides its output if `*print-length*` is set. And it's problematic for most usages of `pr-str` by re-frame-10x and not just that linked line.

A fix would be to use some other serialization approach or to extract all or most calls to `pr-str` into a single function that binds `*print-length*` to `nil`.

### 10x Version

1.7.0

### Reagent Version

-

### React Version

-

### re-frame Version

-

**Comment by kimo-k** [comment]
Thanks for the report.

I think we do use *print-length* in a recent diff. I noticed elsewhere we have used zprint. Probably using zprint everywhere would solve this.

**Comment by kimo-k** [comment]
This should be fixed in 1.8.1
