### ISSUE TITLE
[Bug]: "guide me to greatness" did not guide me to greatness

### ISSUE THREAD

**Issue by enigma** [day8/re-frame-10x#395]
### What happened?

In the timing panel the "guide me to greatness" link does not lead anywhere, upon inspection it does not have any `href` attr.

Is it possibly that https://github.com/day8/re-frame-10x/blob/master/src/day8/re_frame_10x/panels/timing/views.cljs#L59 should use [`rc/hyperlink-href`](https://github.com/day8/re-frame-10x/blob/master/src/day8/re_frame_10x/components/re_com.cljs#L493) instead?

### 10x Version

1.7.0

### Reagent Version

1.2.0

### React Version

18

### re-frame Version

1.2.0

### What browsers are you seeing the problem on?

Chrome

**Comment by kimo-k** [comment]
Thanks, I found a few other places to fix as well.
