### ISSUE TITLE
[Bug]: latest  1.9.8 causes reagent/react console warning for non unique elements

### ISSUE THREAD

**Issue by hipitihop** [day8/re-frame-10x#412]
### What happened?

Console shows the following warning when the "subs" tab is selected or refreshes

```
Warning: Every element in a seq should have a unique :key: ([day8.re_frame_10x.panels.subs.views.pod {:path "[:clipboard-prompt?]", :previous-value false,  .....
```

### Factory Reset

- [ ] yes

### 10x Version

1.9.8

### Reagent Version

1.2.0

### React Version

17.0.2

### re-frame Version

1.4.3

### What browsers are you seeing the problem on?

Chrome

### Relevant console output

```shell
Warning: Every element in a seq should have a unique :key: ....
```

**Comment by kimo-k** [comment]
Hi, so far I can't repro this. We haven't touched that view function in a few years. 
Each pod is keyed by the [reagent-id](https://github.com/day8/re-frame-10x/blob/master/gen-src/day8/re_frame_10x/inlined_deps/re_frame/v1v3v0/re_frame/interop.cljs#L59) of your subscription.

Does your app have two subscriptions with the same reagent-id? Not sure if that's possible, but it would cause the warning.

![image](https://github.com/day8/re-frame-10x/assets/52815698/484a7c8f-3431-4a6b-9d08-c65070e202ce)

**Comment by kimo-k** [comment]
Actually, there can be duplicate keys when the intra-epoch subscriptions are showing. You can see them in that screenshot. I don't get any warning, though.

Could you try out 1.9.9-SNAPSHOT and see if that fixes it?

**Comment by hipitihop** [comment]
Sorry @kimo-k same here, I can no longer reproduce with 1.9.8 or 1.9.9-SNAPSHOT. I generally don't specify keys so unlikely there is a duplicate. Lets ignore for now. Closing
